-- Seed for quiz_options table
INSERT INTO quiz_options (question_id, option_text, is_correct)
VALUES
  (1, 'Paris', true),
  (1, 'Madrid', false),
  (1, 'Berlin', false),
  (1, 'Rome', false),
  (2, 'Jupiter', true),
  (2, 'Mars', false),
  (2, 'Saturn', false),
  (2, 'Venus', false),
  (3, 'William Shakespeare', true),
  (3, 'Charles Dickens', false),
  (3, 'Jane Austen', false),
  (3, 'Mark Twain', false),
  (4, 'H2O', true),
  (4, 'CO2', false),
  (4, 'NaCl', false),
  (4, 'O2', false),
  (5, '7', true),
  (5, '5', false),
  (5, '6', false),
  (5, '8', false),
  (6, '4', true),
  (6, '5', false),
  (6, '6', false),
  (6, '7', false),
  (7, 'Leonardo da Vinci', true),
  (7, 'Pablo Picasso', false),
  (7, 'Vincent van Gogh', false),
  (7, 'Michelangelo', false),
  (8, 'Mars', true),
  (8, 'Venus', false),
  (8, 'Mercury', false),
  (8, 'Earth', false),
  (9, '4', true),
  (9, '2', false),
  (9, '6', false),
  (9, '8', false),
  (10, 'Alan Turing', true),
  (10, 'Isaac Newton', false),
  (10, 'Albert Einstein', false),
  (10, 'Galileo Galilei', false);

--option_text does not match choices in schema
